version: 2
sources:
  - name: austin_bikeshare
    database: bigquery-public-data
    schema: austin_bikeshare
    tables: 
      - name: bikeshare_stations        
      - name: bikeshare_trips

  - name: baseball
    database: bigquery-public-data
    schema: baseball
    tables: 
      - name: games_post_wide        
      - name: games_wide
      - name: schedules

  - name: basketball
    database: bigquery-public-data
    schema: ncaa_basketball
    tables: 
      - name: mbb_historical_tournament_games       
      - name: mbb_historical_teams_games
 